return {
    ["Tranquilas"] = {
		{Name = "El corazon antes que el poder.", ID = "rbxassetid://128660472567732"},
		{Name = "Full metal Alchemist", ID = "rbxassetid://134055865479427"},
		{Name = "Burn my Dread", ID = "rbxassetid://79713395443221"},
		{Name = "7ds, One Love", ID = "rbxassetid://83465768694834"},
		{Name = "Full metal Alchemist", ID = "rbxassetid://134055865479427"},
		{Name = "Love and Light", ID = "rbxassetid://121429995231842"},
		{Name = "Deepspace Overture", ID = "rbxassetid://119650021603699"},
		{Name = "In the Ocean", ID = "rbxassetid://74121201688940"},
		{Name = "Royal Court", ID = "rbxassetid://139186694323000"},
		{Name = "Night Reflections ", ID = "rbxassetid://138749442993417"},
		{Name = "The Eternal Saga", ID = "rbxassetid://138136220523335"},
		{Name = "Soft Rain Melodies", ID = "rbxassetid://137511640484134"},
		{Name = "Viking Voyage", ID = "rbxassetid://132577042741836"},

	},
    ["Combate"] = {
		{Name = "Spliter Wolf", ID = "rbxassetid://117241708883905"},
		{Name = "Titan de Ataque", ID = "rbxassetid://134007668733643"},
		{Name = "Finale", ID = "rbxassetid://93377442126358"},
		{Name = "Death by Glamour", ID = "rbxassetid://138705131180697"},
		{Name = "A Stranger I Remain", ID = "rbxassetid://89522140288647"},
		{Name = "Bakugo vs AFO", ID = "rbxassetid://93773905131307"},
		{Name = "Its Going Down", ID = "rbxassetid://73301000411110"},
		{Name = "Rudo vs Trash", ID = "rbxassetid://119133364555727"},
		{Name = "Its Going Down", ID = "rbxassetid://73301000411110"},
		{Name = "God Games", ID = "rbxassetid://94716148941019"},
		{Name = "Warriors Mind", ID = "rbxassetid://124884160968413"},
		{Name = "Dahillas Theme", ID = "rbxassetid://135989732367470"},

    },
    ["Tristes/Misterio"] = {
		{Name = "Crucified In Heaven", ID = "rbxassetid://103523482013198"},
		{Name = "The Dogs", ID = "rbxassetid://99799050284858"},
		{Name = "Gone Angels - Mili", ID = "rbxassetid://140208821406490"},
		{Name = "Dark Ambient", ID = "rbxassetid://127408623499892"},
		{Name = "Whispers from the Wind", ID = "rbxassetid://137636891376456"},
		{Name = "Scavengers Dawn", ID = "rbxassetid://134297867333782"},
	},
	["Epica/Tranquila"] = {
		{Name = "Noctilucent Calm", ID = "rbxassetid://140648151329276"},
		{Name = "432Hz Sleep", ID = "rbxassetid://140449240163331"},
		{Name = "Space Ambience", ID = "rbxassetid://139992348741850"},
		{Name = "Weightless Echo", ID = "rbxassetid://139478408974589"},
		{Name = "Alpenglow", ID = "rbxassetid://136399909277410"},
		{Name = "Stonehall Stillness", ID = "rbxassetid://136279837164381"},
		{Name = "Harbor of the Wind ", ID = "rbxassetid://131615745306892"},
		{Name = "Tyr's tranquility", ID = "rbxassetid://131241694294164"},
		{Name = "Odin's Oath", ID = "rbxassetid://130800347561846"},

	},
	["Magia"] = {
		{Name = "Liminal Wave", ID = "rbxassetid://132631534724831"},
		{Name = "Bridgerton", ID = "rbxassetid://125623901311030 "},

	},
	["Suspenso"] = {
		{Name = "Anticipation ", ID = "rbxassetid://130727412681283"},
		{Name = "Quiet Suspense", ID = "rbxassetid://138750671396040"},
	}
}
